module.exports = (date) => {
  return `
CASE
    WHEN EXTRACT(MONTH FROM ${date}) = EXTRACT(MONTH FROM CURRENT_DATE()) 
         AND EXTRACT(YEAR FROM ${date}) = EXTRACT(YEAR FROM CURRENT_DATE()) THEN 
        EXTRACT(DAY FROM CURRENT_DATE() - 1) / EXTRACT(DAY FROM DATE_ADD(DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL 1 MONTH) - INTERVAL 1 DAY)
    WHEN EXTRACT(MONTH FROM ${date}) = EXTRACT(MONTH FROM DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH))
         AND EXTRACT(YEAR FROM ${date}) = EXTRACT(YEAR FROM DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH)) THEN 
        1
    ELSE NULL
END
`;
}
