module.exports = () => {
  return `
  (DATE_DIFF(CURRENT_DATE() - 1, DATE_TRUNC(CURRENT_DATE(), YEAR), DAY) + 1) / DATE_DIFF(DATE_TRUNC(DATE_ADD(DATE_TRUNC(CURRENT_DATE(), YEAR), INTERVAL 1 YEAR), DAY), DATE_TRUNC(CURRENT_DATE(), YEAR), DAY)
`;
}
